---
agent: "Maskv3Agent"

train:
  device: "cuda:0"
  logdir: "run/maskv3_coco_deconv"
  n_epochs: 100
  resume: false
  final: false

search:
  active: false
  conf_threshold: [ 0.2, 0.3, 0.4, 0.5 ]
  nms_iou_threshold: [ 0.3, 0.35, 0.4, 0.45 ]

valid:
  when: 80
  conf_threshold: 0.3
  nms_iou_threshold: 0.45

# MS COCO Dataset
dataset:
  size: 416
  scales: [13, 26, 52] # (416//32, 416//16, 416//8)
  n_classes: 80
  # Training data set
  train:
    csv: "download/COCO/train.csv"
    img_root: "download/COCO/images"
    mask_root: "download/COCO/masks"
  # Validation data set
  valid:
    csv: "download/COCO/test.csv"
    img_root: "download/COCO/images"
    mask_root: "download/COCO/masks"
  anchors: [
    [[0.28, 0.22], [0.38, 0.48], [0.9, 0.78]], # Scale #1 anchor box
    [[0.07, 0.15], [0.15, 0.11], [0.14, 0.29]],# Scale #2 anchor box
    [[0.02, 0.03], [0.04, 0.07], [0.08, 0.06]],# Scale #3 anchor box
  ]

dataloader:
  batch_size: 32
  num_workers: 8

# Maskv3 Model
model:
  in_channels: 3
  num_classes: 80
  num_masks: 32
  num_features: 256

# Adam optimizer
optimizer:
  lr: 0.0001
  weight_decay: 0.00001
