---
agent: "YOLOv3Agent"

train:
  device: "cuda:0"
  logdir: "run/yolov3_voc"
  n_epochs: 100
  valid_epoch: 90
  valid_cycle: 3
  resume: false

valid:
  conf_threshold: 0.2
  map_iou_threshold: 0.5
  nms_iou_threshold: 0.45

# PASCAL_VOC Dataset
dataset:
  size: 416
  scales: [13, 26, 52] # (416//32, 416//16, 416//8)
  n_classes: 20
  # Training data set
  train:
    csv: "download/PASCAL_VOC/train.csv"
    img_root: "download/PASCAL_VOC/images"
    label_root: "download/PASCAL_VOC/labels"
  # Validation data set
  valid:
    csv: "download/PASCAL_VOC/test.csv"
    img_root: "download/PASCAL_VOC/images"
    label_root: "download/PASCAL_VOC/labels"
  anchors: [
    [[0.28, 0.22], [0.38, 0.48], [0.9, 0.78]], # Scale #1 anchor box
    [[0.07, 0.15], [0.15, 0.11], [0.14, 0.29]],# Scale #2 anchor box
    [[0.02, 0.03], [0.04, 0.07], [0.08, 0.06]],# Scale #3 anchor box
  ]

dataloader:
  batch_size: 64
  num_workers: 4

# YOLOv3 Model
model:
  in_channels: 3
  num_classes: 20

# Adam optimizer
optimizer:
  lr: 0.001
  weight_decay: 0.0001

# MultiStepLR
scheduler:
  milestones: [60, 90]
  gamma: 0.1
